name: Terraform-destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

# Runner preparations 
permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: eu-west-2 
  TF_VAR_image_tag: ${{ github.sha }}

jobs:
  Terraform-destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
        with: 
          submodules: true 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan -Destroy
        run: terraform plan -destroy -input=false

      - name: Terraform Manual Destroy
        run: terraform destroy -auto-approve -input=false